spring:
  application:
    name: channeling-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:db,s3,oauth,jwt,mail}

matching:
  algorithm:
    base-url: ${MATCHING_ALGORITHM_BASE_URL:http://localhost:8000}

data:
  base-url: ${DATA_BASE_URL:http://localhost:8000}

crawling:
  sync:
    cron: ${CRAWLING_SYNC_CRON:0 0 2 * * *}
